sudo: false
language: node_js
node_js: "10"
services: 
  - postgresql
addons:
  postgresql: "9.6"
env:
  global:
    - CC_TEST_REPORTER_ID=b4302defa4c20e2035d6b50880b67f4834ccbe4bf7708399c730bf652b387a41
cache:
  directories:
  - node_modules
notifications:
  email: false
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coveralls
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: heroku
  api_key: 759e2259-6ed8-413b-86d7-9122e01dc383
  app:
    develop: wayfarertest